// This file is needed for Firebase initialization
// In a real project, it would be generated by the Firebase CLI

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Default options for development
    return const FirebaseOptions(
      apiKey: 'AIzaSyAuQH_8Bu3J0lat6seHvnSGgkfZ_QmR6HY',
      appId: '1:1049215280322:web:b84bc7cbed65ace4a5475b',
      messagingSenderId: '1049215280322',
      projectId: 'sugram-66929',
      storageBucket: 'gs://sugram-66929.firebasestorage.app ',
      authDomain: 'sugram-66929.firebaseapp.com',
    );
  }
}