// This file is needed for Firebase initialization
// In a real project, it would be generated by the Firebase CLI

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Default options for development
    return const FirebaseOptions(
      apiKey: 'demo',
      appId: 'demo',
      messagingSenderId: 'demo',
      projectId: 'demo',
      storageBucket: 'demo',
      authDomain: 'demo',
    );
  }
}